# Array
Un array es una estructura de datos de un mismo tipo organizada en forma de tabla o cuadrícula de distintas dimensiones.

- **Axis**: Cada una de las dimensiones del array
- **Lenght**: El numero de valores que contiene una dimensión del array
- **Index**: La posición que ocupa un valor dentro del array
- **Value**: El valor que contiene el array en un index concreto
- **Rank**: Cuantas dimensiones con tiene el array
- **Size**: El numero de elementos que contiene el array
- **Shape**: El listado de axis con su longitud


In [1]:
import numpy as np #importamos la libreria

In [2]:
#Generar un array vacio con una dimensión de 4 x 8 con valores random de memoria
np.empty((4,8))

array([[5.50410115e-310, 0.00000000e+000, 6.24314969e-310,
        6.24314971e-310, 6.24314969e-310, 6.24314969e-310,
        6.24314738e-310, 6.24314814e-310],
       [6.24314749e-310, 6.24314972e-310, 6.24314971e-310,
        6.24314749e-310, 6.24314737e-310, 6.24314737e-310,
        6.24314737e-310, 6.24314738e-310],
       [6.24314737e-310, 6.24314737e-310, 6.24314738e-310,
        6.24314970e-310, 6.24314738e-310, 6.24314737e-310,
        6.24314737e-310, 6.24314854e-310],
       [6.24314738e-310, 6.24314738e-310, 6.24314738e-310,
        6.24314968e-310, 6.24314972e-310, 6.24314737e-310,
        6.24314968e-310, 6.24314737e-310]])

In [3]:
#Si queremos generar un array con valores 0
np.zeros((4, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
#Si queremos generar con valores 1
np.ones((4, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
#con valores perzonalizados. (7)
np.full((4, 8), 7)

array([[7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [16]:
#arange
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
#arange personalizado
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [20]:
#linspace, numero de elementos dentro del rango
np.linspace(10,20,2)

array([10., 20.])

In [6]:
#Para valores aleatorios con numeros enteros en una dimensión (min, max, size)
np.random.randint(0, 10, 32)

array([4, 8, 1, 9, 2, 5, 9, 5, 0, 9, 0, 6, 9, 9, 2, 2, 1, 0, 9, 1, 3, 5,
       5, 1, 3, 1, 9, 2, 6, 3, 4, 0])

In [7]:
# refermular el array anterior con reshape a un matrix de 4x8
np.reshape(np.random.randint(0, 10, 32), (4, 8))

array([[6, 9, 6, 8, 1, 5, 8, 0],
       [7, 4, 3, 5, 8, 0, 9, 5],
       [5, 3, 1, 5, 2, 1, 8, 0],
       [4, 4, 7, 5, 0, 4, 0, 9]])

In [8]:
#Pasar una lista de python a array de numpy
mi_lista = [4,3,5,6,23,3,4,6,7,2,3,4,6]
np.array(mi_lista)

array([ 4,  3,  5,  6, 23,  3,  4,  6,  7,  2,  3,  4,  6])

In [9]:
#Pasar varias lista de python
lista1 = [0, 5, 1, 9, 8, 2, 7, 6]
lista2 = [3, 2, 7, 9, 6, 8, 6, 9]
lista3 = [4, 8, 0, 4, 7, 8, 1, 1]
lista4 = [5, 6, 5, 1, 8, 7, 4, 3]
mi_array = np.array([lista1, lista2, lista3, lista4])

In [14]:
#cual es el tamaño del arreglo
print(mi_array.size)
#cual es la dimension del arreglo
print(mi_array.ndim)
#cual es la forma del arreglo (filas, columnas)
print(mi_array.shape)
#tipo de datos en el arreglo
print(mi_array.dtype)

32
2
(4, 8)
int64


In [21]:
#Operaciones arimeticas
array1 = np.array(lista1)
array2 = np.array(lista2)
#suma
print(f'Suma: {array1 + array2}')
print(f'Resta: {array1 - array2}')
print(f'Mult: {array1 * array2}')
print(f'Divi: {array1 / array2}')

Suma: [ 3  7  8 18 14 10 13 15]
Resta: [-3  3 -6  0  2 -6  1 -3]
Mult: [ 0 10  7 81 48 16 42 54]
Divi: [0.         2.5        0.14285714 1.         1.33333333 0.25
 1.16666667 0.66666667]


In [12]:
#Funciones de numpy
print(f'Promedio array1 = {array1.mean()}')
print(f'Suma array1 = {array1.sum()}')

Promedio array1 = 4.75
Suma array1 = 38


In [23]:
#concatenar arreglos
cont = np.concatenate((array1, array2))
print(cont)
#ordenarlos
print(np.sort(cont))

[0 5 1 9 8 2 7 6 3 2 7 9 6 8 6 9]
[0 1 2 2 3 5 6 6 6 7 7 8 8 9 9 9]
